/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author wfgu
 */



#include <bits/stdc++.h>

class Task {
public:
	void solve(std::istream& in, std::ostream& out) {
		int T;
		in >> T;
		for (int cas = 1; cas <= T; ++cas) {
			int n, m, k;
			in >> n >> m >> k;

			double result = 0;
			int t = n - m;
			for (int i = 0; i < k; ++i) {
				result += 1.0 * n / (double)(n - t);
				n--;
			}

			printf("Case #%d: %.8lf\n", cas, result);
		}
	}
};


int main() {
	Task solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}
